apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - './infra/k8s/*'
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-mern-dev
  artifacts:
    # - image: us.gcr.io/ticketing-mern-dev/auth
    - image: arun6783/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
